
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"
  config.vm.box_download_insecure=true
  config.vm.network "forwarded_port", guest: 5000, host: 7205

  config.vm.box_check_update = false

  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.name = "ubuntu-local"
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"

    vb.cpus = 1
  end

  
  config.vm.provision "shell", path: "install_dotnet.sh"
  config.vm.provision "shell", path: "install_lab.sh"
  config.vm.provision "shell", path: "startup.sh", run: 'always'

end
